import os
from datetime import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment
from openpyxl.utils import get_column_letter
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from app.core.config import settings

LOGO_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "assets", "logo-icon.png")

LEADS_DIR = os.path.join(settings.LOCAL_STORAGE_PATH, "reports")
os.makedirs(LEADS_DIR, exist_ok=True)

CHARCOAL_FILL = PatternFill(start_color="183B66", end_color="183B66", fill_type="solid")
HEADER_FONT = Font(color="64A844", bold=True, size=11)
CHARCOAL = colors.HexColor("#183B66")
AMBER = colors.HexColor("#64A844")
INK = colors.HexColor("#1B1613")
GREY = colors.HexColor("#888888")

COLUMNS = ["Customer Code", "Name", "Phone", "Branch", "KYC", "Phone Verified", "Loan Status", "Loan Amount (₹)", "Applied Date"]


def generate_leads_xlsx(tenant_name: str, leads: list[dict]) -> str:
    wb = Workbook()
    ws = wb.active
    ws.title = "Customer Leads"

    ws.merge_cells("A1:I1")
    ws["A1"] = f"Udhayam MFI — {tenant_name} — Customer Leads"
    ws["A1"].font = Font(bold=True, size=14)
    ws["A2"] = f"Generated {datetime.utcnow().strftime('%d %b %Y, %I:%M %p UTC')} — {len(leads)} leads"
    ws["A2"].font = Font(italic=True, size=9, color="888888")

    header_row = 4
    for col, text in enumerate(COLUMNS, start=1):
        cell = ws.cell(row=header_row, column=col, value=text)
        cell.fill = CHARCOAL_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center")

    for i, lead in enumerate(leads, start=header_row + 1):
        ws.cell(row=i, column=1, value=lead["customer_code"])
        ws.cell(row=i, column=2, value=lead["full_name"])
        ws.cell(row=i, column=3, value=lead["phone"])
        ws.cell(row=i, column=4, value=lead["branch_name"])
        ws.cell(row=i, column=5, value="Yes" if lead["kyc_verified"] else "No")
        ws.cell(row=i, column=6, value="Yes" if lead["phone_verified"] else "No")
        ws.cell(row=i, column=7, value=lead["loan_status"] or "—")
        ws.cell(row=i, column=8, value=lead["loan_amount"] or "")
        ws.cell(row=i, column=9, value=lead["applied_date"] or "")

    for col in range(1, len(COLUMNS) + 1):
        ws.column_dimensions[get_column_letter(col)].width = 18

    filename = f"leads-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.xlsx"
    file_path = os.path.join(LEADS_DIR, filename)
    wb.save(file_path)
    return file_path


def generate_leads_pdf(tenant_name: str, leads: list[dict]) -> str:
    filename = f"leads-{datetime.utcnow().strftime('%Y%m%d-%H%M%S')}.pdf"
    file_path = os.path.join(LEADS_DIR, filename)
    c = canvas.Canvas(file_path, pagesize=landscape(A4))
    width, height = landscape(A4)

    c.setFillColor(CHARCOAL)
    c.rect(0, height - 22 * mm, width, 22 * mm, fill=1, stroke=0)

    if os.path.exists(LOGO_PATH):
        from reportlab.lib.utils import ImageReader
        logo_size = 14 * mm
        c.drawImage(
            ImageReader(LOGO_PATH), 14 * mm, height - 18 * mm, width=logo_size, height=logo_size,
            mask="auto", preserveAspectRatio=True,
        )
        text_x = 14 * mm + logo_size + 4 * mm
    else:
        text_x = 14 * mm

    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(text_x, height - 12 * mm, "UDHAYAM MFI")
    c.setFont("Helvetica", 10)
    c.drawString(text_x, height - 18 * mm, f"Customer Leads — {tenant_name} — {len(leads)} leads")

    col_x = [14, 60, 100, 140, 175, 205, 225, 255, 280]
    headers = ["Code", "Name", "Phone", "Branch", "KYC", "Phone", "Status", "Amount", "Applied"]

    y = height - 30 * mm
    c.setFont("Helvetica-Bold", 8)
    c.setFillColor(GREY)
    for x, h in zip(col_x, headers):
        c.drawString(x * mm, y, h)
    y -= 6 * mm

    c.setFont("Helvetica", 8)
    for lead in leads:
        if y < 15 * mm:
            c.showPage()
            y = height - 20 * mm
            c.setFont("Helvetica", 8)
        c.setFillColor(INK)
        row = [
            lead["customer_code"], lead["full_name"][:20], lead["phone"], (lead["branch_name"] or "—")[:15],
            "Yes" if lead["kyc_verified"] else "No", "Yes" if lead["phone_verified"] else "No",
            (lead["loan_status"] or "—")[:14], str(lead["loan_amount"] or ""), (lead["applied_date"] or ""),
        ]
        for x, val in zip(col_x, row):
            c.drawString(x * mm, y, str(val))
        y -= 5.5 * mm

    c.setFillColor(GREY)
    c.setFont("Helvetica-Oblique", 7)
    c.drawCentredString(width / 2, 8 * mm, "Generated by Udhayam MFI")
    c.showPage()
    c.save()
    return file_path
