import os
from datetime import datetime
from reportlab.lib.pagesizes import A5
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas

from app.core.config import settings

PAYSLIPS_DIR = os.path.join(settings.LOCAL_STORAGE_PATH, "payslips")
os.makedirs(PAYSLIPS_DIR, exist_ok=True)

INK = colors.HexColor("#1B1613")
CHARCOAL = colors.HexColor("#231F20")
AMBER = colors.HexColor("#FFB600")
GREY = colors.HexColor("#888888")


def generate_payslip_pdf(payslip, employee, month: str) -> str:
    filename = f"payslip-{payslip.id}.pdf"
    file_path = os.path.join(PAYSLIPS_DIR, filename)
    c = canvas.Canvas(file_path, pagesize=A5)
    width, height = A5

    c.setFillColor(CHARCOAL)
    c.rect(0, height - 25 * mm, width, 25 * mm, fill=1, stroke=0)
    c.setFillColor(AMBER)
    c.setFont("Helvetica-Bold", 16)
    c.drawString(12 * mm, height - 12 * mm, "OS FINANCES")
    c.setFillColor(colors.white)
    c.setFont("Helvetica", 9)
    c.drawString(12 * mm, height - 18 * mm, f"Payslip — {month}")

    y = height - 35 * mm
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(12 * mm, y, employee.full_name if employee else "—")
    c.setFont("Helvetica", 9)
    c.drawString(12 * mm, y - 6 * mm, employee.designation or "")

    y -= 18 * mm
    rows = [
        ("Basic Salary", f"Rs. {payslip.basic_salary:,.2f}"),
        ("Allowances", f"Rs. {payslip.allowances or 0:,.2f}"),
        ("Deductions", f"- Rs. {payslip.deductions or 0:,.2f}"),
    ]
    for label, value in rows:
        c.setFont("Helvetica", 9)
        c.drawString(12 * mm, y, label)
        c.drawRightString(width - 12 * mm, y, value)
        y -= 8 * mm

    y -= 3 * mm
    c.setStrokeColor(colors.HexColor("#DDDDDD"))
    c.line(12 * mm, y, width - 12 * mm, y)
    y -= 10 * mm

    c.setFont("Helvetica-Bold", 13)
    c.setFillColor(CHARCOAL)
    c.drawString(12 * mm, y, "Net Pay:")
    c.drawRightString(width - 12 * mm, y, f"Rs. {payslip.net_pay:,.2f}")

    y -= 15 * mm
    c.setFont("Helvetica", 8)
    c.setFillColor(GREY)
    status_line = f"Status: {payslip.status.value.upper()}"
    if payslip.paid_at:
        status_line += f" — {payslip.paid_at.strftime('%d %b %Y')}"
    if payslip.payment_reference:
        status_line += f" — Ref: {payslip.payment_reference}"
    c.drawString(12 * mm, y, status_line)

    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(width / 2, 12 * mm, "Generated by OS Finances — an OS2 Studio product")

    c.showPage()
    c.save()
    return file_path
